// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqNAP5K2jxkKEzRFFrTzugSoopWm_QuvA',
    appId: '1:9951046384:android:fa69b1f1ef01836b9eb035',
    messagingSenderId: '9951046384',
    projectId: 'alsaie-5a145',
    databaseURL: 'https://alsaie-5a145-default-rtdb.firebaseio.com',
    storageBucket: 'alsaie-5a145.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuHeHabBRtKNeHmIryBM1PfowJLeMFMfo',
    appId: '1:9951046384:ios:240ea54844cc77149eb035',
    messagingSenderId: '9951046384',
    projectId: 'alsaie-5a145',
    databaseURL: 'https://alsaie-5a145-default-rtdb.firebaseio.com',
    storageBucket: 'alsaie-5a145.appspot.com',
    androidClientId: '9951046384-k36kun10u8dkde7pbs27tp3v39nf0mp9.apps.googleusercontent.com',
    iosClientId: '9951046384-jg3b3nine3gnqfehbnms0kq1p9an0d93.apps.googleusercontent.com',
    iosBundleId: 'com.example.diagnoplus',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX9FM9iHK6CmS1RGByOnbfe0i8ECsdjaU',
    appId: '1:9951046384:web:c99d5a3532a44fdb9eb035',
    messagingSenderId: '9951046384',
    projectId: 'alsaie-5a145',
    authDomain: 'alsaie-5a145.firebaseapp.com',
    databaseURL: 'https://alsaie-5a145-default-rtdb.firebaseio.com',
    storageBucket: 'alsaie-5a145.appspot.com',
    measurementId: 'G-213VTLE4V0',
  );

}